#pragma once
#define CREATE_NEW_MINDMAP_MODE 49
#define INSERT_NEW_NODE_MODE 50
#define DISPLAY_MODE 51
#define SAVE_MIND_MAP_MODE 52
#define EXIT_MODE 125
#define MESSANGE_MODE 126

#define SELECT_INSERT_MODE 127
#define ENTER_NODE_NAME_MODE 128
