#pragma once
#define ERROR_INPUT_MSG "Error Input!\n\n"
#define ERROR_ROOT_INSERT_PARENT "Root can't insert parent node\n"
#define ERROR_ROOT_INSERT_SIBLING "Root can't insert sibling node\n"
#define ERROR_DO_OPERATION "Can not do this operation.\n"
#define THE_MIND_MAP "The mind map "
#define DISPLAY_MINDMAP " is displayed as follows:"
#define SAVE_FILE_NAME "mindMap.txt"
#define SAVE_FILE_SUCCESS "Save MindMap Success!\n\n"
#define ERROR_OPEN_FILE "Can't not open file!\n"
#define EMPTY_STRING ""
#define SPACE_STRING " "
#define DOUBLE_QUOTATION_STRING "\""
#define NODE_TYPE "Node"
#define ROOT_TYPE "Root"
#define PROMPT_STRING ">"
