#pragma once
#define ERROR_INPUT_MSG "Error Input!\n\n"
#define ERROR_INPUT_COMMAND "The command is not found!!\n\n"
#define ERROR_ROOT_INSERT_PARENT "Root can't insert parent node\n"
#define ERROR_ROOT_INSERT_SIBLING "Root can't insert sibling node\n"
#define ERROR_ROOT_CHANGE_PARENT "Root can't be change parent!\n"
#define ERROR_ROOT_DELETE "Root can't be delete!\n"
#define ERROR_DISPLAY "MindMap is Empty, can't display!!!\n"
#define ERROR_SAVE "MindMap is Empty, can't save!!!\n"
#define ERROR_NODE_NOTFOUND "The node is not exist!! \n"
#define ERROR_SELECT_NODE "The node is not exist!!\n"
#define ERROR_SELECT_ITSELF "You can't select itself!!\n"
#define ERROR_INPUT_CHAR "You can't input the char\n"
#define ERROR_REDO "Can't redo!\n"
#define ERROR_UNDO "Can't undo!\n"
#define THE_MIND_MAP "The mind map "
#define DISPLAY_MINDMAP " is displayed as follows:"
#define SAVE_FILE_NAME "mindMap.mm"
#define SAVE_FILE_SUCCESS "Save MindMap Success!\n\n"
#define ERROR_OPEN_FILE "Can't not open file!\n"
#define EMPTY_STRING ""
#define SPACE_STRING " "
#define DOUBLE_QUOTATION_STRING "\""
#define NODE_TYPE "Node"
#define ROOT_TYPE "Root"
#define PROMPT_STRING ">"
